### ISSUE TITLE
Problem with newest Raspi 4 version

### ISSUE THREAD

**Issue by Jannes272** [janwolzenburg/divera247-raspberry-pi#1]
Thank you for this great work, tho I had some  Problems implementing it on the raspi4 that we got.
Sometihg with the autostart sems to be off...
After a lot of trouble the solution we found, was not to use the newest 64bit version but the 32bit Legacy version.
The 32bit Legacy runs Perfect since installation.
I only wantet to add these so other users can save them from the trouble we got.
Greedings

**Comment by janwolzenburg** [comment]
The newest Raspian distribution with Debian 12 Bookworm uses a different method for autostarts (https://forums.raspberrypi.com/viewtopic.php?t=357858&sid=77ed5c8bed80736e92b9f57351e4904b).
The legacy version uses Debian 11 Bullseye, where this autostart method works.
I updated the Readme with information about the autostart problem. Thank you for the hint.
DIVERA now offers a standalone application (https://help.divera247.com/display/FAQ/Monitor+Desktop+App) you could consider using in the future. It has some nice features.
Greetings

**Comment by fechnert** [comment]
@Jannes272 for the raspi 4 and newer i switched to [FullPageOS](https://github.com/guysoft/FullPageOS) due to similar issues i had with the move from X11 to wayland. Maybe that's worth a try.
